add and update feature extraction code
SarderLab/Multi-Compartment-Segmentation pull request #14
Opened 2023-06-29 16:41 UTC by sayatmimar

This PR updates feature extraction code and calculates mesangial area within the mask boundary for glom regions. The code also refactors the `glom` and `s_glom` into one single function within `PAS_deconvolution.py`.

2023-07-06 22:22 UTC, anindya-paul requested changes
Please look at my comments. Thank you all for helping!

2023-07-06 22:22 UTC, anindya-paul commented on histomicstk/cli/FeatureExtraction/FeatureExtraction.py
@njlucare: overall the bigger issue I see in our feature extraction code is there are so many hardcoded threshold values and all threshold values that Brandon/Brendon set have been changed. What I think is these threshold numbers are dependent on the specific WSI images collected by different cohorts. Even if we assume PAS-H staining only, still there is a variety of KPMP uploaded images by different cohorts, so I'm inclined to give user an option to update these threshold values as they feel necessary. Instead of command line arguments, I was thinking of Yml config ([Hydra](https://hydra.cc/docs/tutorials/basic/your_first_app/config_file/) makes this so simple) that the code will make use of. @sayatmimar gave another idea of creating input parameter boxes in HistomicsUI to provide easier access to a user which I support. Before we create those input parameter boxes in UI, we need to name each threshold for better understanding. Could you please look at extraction of glom, tubule, and arterioles feature extraction portions and help us choosing suitable names of thresholds so we can start adding them in the HistomicsUI?

2023-07-07 12:48 UTC, njlucare commented on histomicstk/cli/FeatureExtraction/FeatureExtraction.py
>      tubules = mask_xml == 5
Sure

2023-07-07 12:58 UTC, njlucare commented on histomicstk/cli/FeatureExtraction/FeatureExtraction.py
h threshold, pas threshold, saturation threshold

2023-07-07 16:47 UTC, sayatmimar commented on histomicstk/cli/FeatureExtraction/FeatureExtraction.py
>      annotations = gc.get('/annotation/item/{}'.format(file_id))
@anindya-paul it's a few lines above on L51-52 where I define girder_client.

2023-07-07 19:10 UTC, sayatmimar commented on histomicstk/segmentationschool/Codes/IterativePredict_1X.py
> +        unique_mask.extend(np.unique(wsiMask[i:i + 7000]))
This is from the original code. Looks like we extract `annotationID's` from the mask. And @anindya-paul  no worries, I pulled the updates in `IteraivePredict_1X.py` on this branch.

2023-07-07 19:14 UTC, anindya-paul approved these changes
LGTM!

2023-07-07 19:57 UTC, anindya-paul commented
LGTM! Great job @sayatmimar and @njlucare thank you!!

2023-07-07 19:59 UTC, merged