Remove os system cmd
SarderLab/Multi-Compartment-Segmentation pull request #27
Opened 2024-02-06 17:56 UTC by spborder

Fixes spaces/odd characters in file names issue. Creates importable "run_it" function. Updates names of some arguments for consistency.

2024-02-23 00:20 UTC, sayatmimar requested changes
See my comment. Have you built the docker and tested this code in DSA?

2024-02-23 00:20 UTC, sayatmimar commented on multic/cli/MultiCompartmentSegment/MultiCompartmentSegment.py
> +    }
We can move this outside of the function to the top. You can also call it `DEFAULT_VALS`. As default `args` are now stored in this dictionary, we don't need to parse them in `segmentation_school` right? If so let's delete parsing in `segmentation_school`.

2024-02-27 23:33 UTC, spborder commented
Fixed, updated image, tested on EC2 and all looks good.

Completed Job: http://ec2-3-230-122-132.compute-1.amazonaws.com:8080/#job/65de6cd8adb89a58fea10d7c
Test Image: http://ec2-3-230-122-132.compute-1.amazonaws.com:8080/#item/659c269b4e590bbcdeb406cc

2024-02-28 16:42 UTC, sayatmimar approved these changes
LGTM

2024-05-31 19:27 UTC, merged